# Generated by Django 5.2.1 on 2025-05-21 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CPU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "part_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("brand", models.CharField(blank=True, max_length=255, null=True)),
                ("model", models.CharField(max_length=255)),
                ("rank", models.IntegerField(blank=True, null=True)),
                ("benchmark", models.FloatField(blank=True, null=True)),
                ("samples", models.IntegerField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("image_url", models.URLField(blank=True, null=True)),
                ("frequency", models.CharField(blank=True, max_length=255, null=True)),
                ("cores", models.CharField(blank=True, max_length=255, null=True)),
                ("socket", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "unlocked_multiplier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GPU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("brand", models.CharField(blank=True, max_length=255, null=True)),
                ("model", models.CharField(blank=True, max_length=255, null=True)),
                ("rank", models.FloatField(blank=True, null=True)),
                ("benchmark", models.FloatField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("chipset", models.CharField(blank=True, max_length=255, null=True)),
                ("ram", models.CharField(blank=True, max_length=255, null=True)),
                ("dlugosc", models.CharField(blank=True, max_length=255, null=True)),
                ("taktowanie", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "part_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("samples", models.FloatField(blank=True, null=True)),
                ("img_src", models.URLField(blank=True, null=True)),
                ("link_produkt_href", models.URLField(blank=True, null=True)),
                (
                    "recomended_ps",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Producer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Motherboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("mpn", models.CharField(blank=True, max_length=255, null=True)),
                ("ean", models.CharField(blank=True, max_length=255, null=True)),
                ("upc", models.CharField(blank=True, max_length=255, null=True)),
                ("socket", models.CharField(blank=True, max_length=255, null=True)),
                ("chipset", models.CharField(blank=True, max_length=255, null=True)),
                ("unlocked", models.BooleanField(blank=True, null=True)),
                (
                    "form_factor",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "memory_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "memory_capacity",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ram_slots", models.IntegerField(blank=True, null=True)),
                ("sata", models.IntegerField(blank=True, null=True)),
                ("vga", models.IntegerField(blank=True, null=True)),
                ("dvi", models.FloatField(blank=True, null=True)),
                ("display_port", models.FloatField(blank=True, null=True)),
                ("hdmi", models.FloatField(blank=True, null=True)),
                ("wifi", models.BooleanField(blank=True, null=True)),
                ("integrated_graphics", models.BooleanField(blank=True, null=True)),
                ("product_page", models.URLField(blank=True, null=True)),
                (
                    "producer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hardware.producer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HDD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("mpn", models.CharField(blank=True, max_length=255, null=True)),
                ("ean", models.CharField(blank=True, max_length=255, null=True)),
                ("upc", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "form_factor",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("size", models.CharField(blank=True, max_length=255, null=True)),
                ("rpm", models.FloatField(blank=True, null=True)),
                ("cache", models.CharField(blank=True, max_length=255, null=True)),
                ("product_page", models.URLField(blank=True, null=True)),
                (
                    "producer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hardware.producer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CPUCooler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("mpn", models.CharField(blank=True, max_length=255, null=True)),
                ("ean", models.CharField(blank=True, max_length=255, null=True)),
                ("upc", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "supported_sockets",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("height", models.IntegerField(blank=True, null=True)),
                ("tdp", models.IntegerField(blank=True, null=True)),
                ("fans_80mm", models.IntegerField(blank=True, null=True)),
                ("fans_92mm", models.IntegerField(blank=True, null=True)),
                ("fans_120mm", models.IntegerField(blank=True, null=True)),
                ("fans_140mm", models.IntegerField(blank=True, null=True)),
                ("fans_200mm", models.IntegerField(blank=True, null=True)),
                ("additional_fan_support", models.BooleanField(blank=True, null=True)),
                ("product_page", models.URLField(blank=True, null=True)),
                (
                    "producer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hardware.producer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComputerCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("mpn", models.CharField(blank=True, max_length=255, null=True)),
                ("ean", models.CharField(blank=True, max_length=255, null=True)),
                ("upc", models.CharField(blank=True, max_length=255, null=True)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("depth", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                (
                    "motherboard",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "power_supply",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("supported_gpu_length", models.IntegerField(blank=True, null=True)),
                (
                    "supported_cpu_cooler_height",
                    models.IntegerField(blank=True, null=True),
                ),
                ("fans_80mm", models.CharField(blank=True, max_length=50, null=True)),
                ("fans_120mm", models.CharField(blank=True, max_length=50, null=True)),
                ("fans_140mm", models.CharField(blank=True, max_length=50, null=True)),
                ("fans_200mm", models.CharField(blank=True, max_length=50, null=True)),
                ("radiator_120mm", models.FloatField(blank=True, null=True)),
                ("radiator_140mm", models.FloatField(blank=True, null=True)),
                ("radiator_240mm", models.FloatField(blank=True, null=True)),
                ("radiator_280mm", models.FloatField(blank=True, null=True)),
                ("radiator_360mm", models.FloatField(blank=True, null=True)),
                ("disk_25", models.IntegerField(blank=True, null=True)),
                ("disk_35", models.IntegerField(blank=True, null=True)),
                ("disk_25_35", models.IntegerField(blank=True, null=True)),
                ("disk_525", models.IntegerField(blank=True, null=True)),
                (
                    "primary_color",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("window", models.BooleanField(blank=True, null=True)),
                ("dust_filter", models.BooleanField(blank=True, null=True)),
                ("cable_management", models.BooleanField(blank=True, null=True)),
                ("noise_isolation", models.BooleanField(blank=True, null=True)),
                ("product_page", models.URLField(blank=True, null=True)),
                (
                    "producer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hardware.producer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PSU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("mpn", models.CharField(blank=True, max_length=255, null=True)),
                ("ean", models.CharField(blank=True, max_length=255, null=True)),
                ("upc", models.CharField(blank=True, max_length=255, null=True)),
                ("watt", models.CharField(blank=True, max_length=255, null=True)),
                ("size", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "efficiency_rating",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("product_page", models.URLField(blank=True, null=True)),
                (
                    "producer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hardware.producer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RAM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("mpn", models.CharField(blank=True, max_length=255, null=True)),
                ("ean", models.CharField(blank=True, max_length=255, null=True)),
                ("upc", models.CharField(blank=True, max_length=255, null=True)),
                ("ram_type", models.CharField(blank=True, max_length=255, null=True)),
                ("size", models.CharField(blank=True, max_length=255, null=True)),
                ("clock", models.IntegerField(blank=True, null=True)),
                ("timings", models.CharField(blank=True, max_length=255, null=True)),
                ("sticks", models.IntegerField(blank=True, null=True)),
                ("product_page", models.URLField(blank=True, null=True)),
                (
                    "producer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hardware.producer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SSD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("mpn", models.CharField(blank=True, max_length=255, null=True)),
                ("ean", models.CharField(blank=True, max_length=255, null=True)),
                ("upc", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "form_factor",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("protocol", models.CharField(blank=True, max_length=255, null=True)),
                ("size", models.CharField(blank=True, max_length=255, null=True)),
                ("nand", models.CharField(blank=True, max_length=255, null=True)),
                ("controller", models.CharField(blank=True, max_length=255, null=True)),
                ("product_page", models.URLField(blank=True, null=True)),
                (
                    "producer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hardware.producer",
                    ),
                ),
            ],
        ),
    ]
