# Generated by Django 5.2.4 on 2025-08-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gpu",
            options={
                "verbose_name": "Karta graficzna",
                "verbose_name_plural": "Karty graficzne",
            },
        ),
        migrations.AlterField(
            model_name="gpu",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
