# Generated by Django 5.2.4 on 2025-08-21 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0002_alter_gpu_options_alter_gpu_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserComputer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nazwa zestawu"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Opis"),
                ),
                ("cpu_name", models.CharField(max_length=200, verbose_name="Procesor")),
                (
                    "gpu_name",
                    models.CharField(max_length=200, verbose_name="Karta graficzna"),
                ),
                (
                    "motherboard_name",
                    models.CharField(max_length=200, verbose_name="Płyta główna"),
                ),
                (
                    "ram_name",
                    models.CharField(max_length=200, verbose_name="Pamięć RAM"),
                ),
                (
                    "psu_watt",
                    models.IntegerField(default=500, verbose_name="Moc PSU (W)"),
                ),
                (
                    "ssd_size",
                    models.IntegerField(default=512, verbose_name="Rozmiar SSD (GB)"),
                ),
                (
                    "hdd_size",
                    models.IntegerField(default=0, verbose_name="Rozmiar HDD (GB)"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="user_computers/",
                        verbose_name="Zdjęcie zestawu",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="Publiczny zestaw"),
                ),
                (
                    "allow_comments",
                    models.BooleanField(
                        default=True, verbose_name="Zezwalaj na komentarze"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "views_count",
                    models.IntegerField(default=0, verbose_name="Liczba wyświetleń"),
                ),
                (
                    "likes_count",
                    models.IntegerField(default=0, verbose_name="Liczba polubień"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="computers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Komputer użytkownika",
                "verbose_name_plural": "Komputery użytkowników",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserComputerComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Treść komentarza")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "computer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="hardware.usercomputer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserComputerLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "computer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="hardware.usercomputer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "computer")},
            },
        ),
    ]
