# Generated by Django 5.2.4 on 2025-08-21 08:14

import hardware.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0003_usercomputer_usercomputercomment_usercomputerlike"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercomputer",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=hardware.models.user_computer_image_path,
                verbose_name="Zdjęcie zestawu",
            ),
        ),
    ]
